# Generated by Django 4.2.19 on 2025-02-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_client_user_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
